#include<vector>
using std::vector;
#include <stdio.h>
#include <fstream>

extern long long cycle_num;
extern bool replay_stall;
//initialise vector of vectors as stallData[Warp #][stall #]
extern vector<vector<vector<int>>>stallData;
extern vector<vector<int>>act_warp;
extern vector<vector<int>>issued_warp;
extern vector<vector<vector<int>>> str_status;
extern vector<int>warp_issue;
extern vector<int>icnt_pressure;
extern vector<unsigned>warp_inst_num;
extern vector<int>warps_cannot_be_issued;
extern vector<int> indep_pc_num_push_all_stalling_inst;
extern vector<int>stall_consolidated;

extern std::ofstream write_warps;
extern std::ofstream test_write_warps;
extern long long max_active;
extern long long actw;
extern long long max_warps_act;
extern long long max_sid;
extern long long num_of_schedulers;
extern long long numstall;
extern long long cycles_passed;
extern long long inst_counter;
extern long long print_on;
extern long long going_from_shader_to_mem;
extern long long stall_cycles;
extern long long tot_icnt_buffer;
extern long long tot_inst_exec;
extern long long tot_cycles_exec_all_SM;
extern long long tot_inst_ret;
extern int total_warps;

// Stats collection
extern long long  mem_data_stall;
extern long long  comp_data_stall;
extern long long  ibuffer_stall;
extern long long  comp_str_stall;
extern long long  mem_str_stall;
extern long long  other_stall1;
extern long long  other_stall2;
extern long long  other_stall3;
extern long long  mem_data_stall_kernel;
extern long long  comp_data_stall_kernel;
extern long long  ibuffer_stall_kernel;
extern long long  comp_str_stall_kernel;
extern long long  mem_str_stall_kernel;
extern long long  other_stall1_kernel;
extern long long  other_stall2_kernel;
extern long long  other_stall3_kernel;
extern long long ooo_opp_kernel;
extern long long mem_data_stall_issue_irr;
extern long long comp_data_stall_issue_irr;
extern long long ibuffer_stall_issue_irr;
extern long long comp_str_stall_issue_irr;
extern long long mem_str_stall_issue_irr;
extern long long other_stall_issue_irr1;
extern long long other_stall_issue_irr2;
extern long long other_stall_issue_irr3;
extern long long ICNT_TO_MEM_count;
extern long long ICNT_TO_MEM_count_kernel;
extern long long ICNT_TO_MEM_cycles;
extern long long ICNT_TO_MEM_cycles_kernel;
extern long long ROP_DELAY_count;
extern long long ROP_DELAY_cycle;
extern long long ROP_DELAY_count_kernel;
extern long long ROP_DELAY_cycle_kernel;
extern long long ICNT_TO_L2_QUEUE_count;
extern long long ICNT_TO_L2_QUEUE_count_kernel;
extern long long ICNT_TO_L2_QUEUE_cycles;
extern long long ICNT_TO_L2_QUEUE_cycles_kernel;
extern long long L2_TO_DRAM_QUEUE_count;
extern long long L2_TO_DRAM_QUEUE_cycle;
extern long long DRAM_LATENCY_QUEUE_count;
extern long long DRAM_LATENCY_QUEUE_cycle;
extern long long DRAM_LATENCY_QUEUE_count_kernel;
extern long long DRAM_LATENCY_QUEUE_cycle_kernel;
extern long long DRAM_TO_L2_QUEUE_count;
extern long long DRAM_TO_L2_QUEUE_count_kernel;
extern long long DRAM_TO_L2_QUEUE_cycle;
extern long long DRAM_TO_L2_QUEUE_cycle_kernel;
extern long long DRAM_L2_FILL_QUEUE_count;
extern long long DRAM_L2_FILL_QUEUE_cycle;
extern long long DRAM_L2_FILL_QUEUE_count_kernel;
extern long long DRAM_L2_FILL_QUEUE_cycle_kernel;
extern long long L2_TO_ICNT_count;
extern long long L2_TO_ICNT_cycle;
extern long long L2_TO_ICNT_count_kernel;
extern long long L2_TO_ICNT_cycle_kernel;
extern long long CLUSTER_TO_SHADER_QUEUE_count;
extern long long CLUSTER_TO_SHADER_QUEUE_cycle;
extern long long CLUSTER_TO_SHADER_QUEUE_count_kernel;
extern long long CLUSTER_TO_SHADER_QUEUE_cycle_kernel;
extern long long CLUSTER_TO_SHADER_QUEUE_1_count;
extern long long CLUSTER_TO_SHADER_QUEUE_1_cycle;
extern long long mem_issues;
extern long long mem_cycle_counter;
extern long long l2_cache_bank_access;
extern long long l2_cache_bank_miss;
extern long long l2_cache_access;
extern long long l2_cache_miss;
extern long long l2_pending;
extern long long l2_res_fail;
extern long long c_mem_resource_stall;
extern long long s_mem_bk_conf;
extern long long gl_mem_resource_stall;
extern long long gl_mem_coal_stall;
extern long long gl_mem_data_port_stall;
extern long long icnt_creat_inj;
extern long long icnt_creat_arrival;
extern long long icnt_inj_arrival;
extern long long icnt_creat_inj_READ_REQUEST;
extern long long icnt_creat_arrival_READ_REQUEST;
extern long long icnt_inj_arrival_READ_REQUEST;
extern long long icnt_creat_inj_WRITE_REQUEST;
extern long long icnt_creat_arrival_WRITE_REQUEST;
extern long long icnt_inj_arrival_WRITE_REQUEST;
extern long long icnt_creat_inj_READ_REPLY;
extern long long icnt_creat_arrival_READ_REPLY;
extern long long icnt_inj_arrival_READ_REPLY;
extern long long icnt_creat_inj_WRITE_REPLY;
extern long long icnt_creat_arrival_WRITE_REPLY;
extern long long icnt_inj_arrival_WRITE_REPLY;
extern long long icnt_mem_total_time_spend_Ishita;
extern long long L2_cache_access_total_Ishita;
extern long long L2_cache_access_miss_Ishita;
extern long long L2_cache_access_pending_Ishita;
extern long long L2_cache_access_resfail_Ishita;
extern long long simple_dram_count;
extern long long delay_tot_sum;
extern long long hits_num_total;
extern long long access_num_total;
extern long long hits_read_num_total;
extern long long read_num_total;
extern long long hits_write_num_total;
extern long long write_num_total;
extern long long banks_1time_total;
extern long long banks_acess_total_Ishita;
extern long long banks_time_rw_total;
extern long long banks_access_rw_total_Ishita;
extern long long banks_time_ready_total;
extern long long banks_access_ready_total_Ishita;
extern long long bwutil_total;
extern long long checked_L2_DRAM_here;
extern long long ICNT_TO_SHADER_count;
extern long long ICNT_TO_SHADER_cycles;
extern long long ICNT_TO_SHADER_count_kernel;
extern long long ICNT_TO_SHADER_cycles_kernel;
extern bool print_stall_data;
extern long long SHADER_ICNT_PUSH;
extern long long mem_inst_issue;
extern long long comp_inst_issue;
extern long long issued_inst_count;
extern long long shared_cycle_count;
extern long long constant_cycle_count;
extern long long texture_cycle_count;
extern long long memory_cycle_count;
extern long long shared_cycle_cycle;
extern long long constant_cycle_cycle;
extern long long texture_cycle_cycle;
extern long long memory_cycle_cycle;
extern long long texture_issue_cycle;
extern long long memory_issue_cycle;
extern long long pushed_from_shader_icnt_l2_icnt;
extern long long tex_icnt_l2_queue;
extern long long icnt_ROP_queue;
extern long long l2_queue_pop;
extern long long l2_queue_reply;
extern long long l2_dram_push;
extern long long l2_dram_rop;
extern long long l2_icnt_push;
extern long long l2_dram_queue_pop;
extern long long push_in_dram;
extern long long push_from_dram;
extern long long dram_l2_reached;
extern long long icnt_back_to_shader;
extern long long reached_shader_from_icnt;
extern long long reach_tex_from_l2;
extern long long reach_glob_from_icnt;
extern long long reach_L1_from_tex;
extern long long reached_global_from_glob;
extern long long finish_inst;
extern long long ROP_no_push_l2_queue_push;
extern long long ROP_extra_cycles;
extern long long l2_dram_rop_count;
extern long long NO_INST_ISSUE;
extern long long opp_for_ooo;
extern long long opp_for_mem;
extern long long dram_access_total;
extern long long dram_write_req_total;
extern long long dram_read_req_total;

// MEM STATS COLLECTION
extern long long total_row_accesses_NET;
extern long long total_num_activates_NET;
extern long long tot_DRAM_reads;
extern long long tot_DRAM_writes;
extern long long gpu_stall_dramfull_total;
extern long long gpu_stall_icnt2sh_total;
extern long long mf_total_lat_tot;
extern long long num_mfs_tot;
extern long long icnt2mem_latency_tot;
extern long long icnt2sh_latency_tot;
extern long long n_act_tot;
extern long long n_pre_tot;
extern long long n_req_tot;
extern long long n_rd_tot;
extern long long n_wr_tot;
extern long long total_dL1_misses;
extern long long total_dL1_accesses;
extern long long L2_total_cache_accesses;
extern long long L2_total_cache_pending_hits;
extern long long L2_total_cache_reservation_fails;
extern long long L1I_total_cache_accesses;
extern long long L1I_total_cache_misses;
extern long long L1I_total_cache_pending_hits;
extern long long L1I_total_cache_reservation_fails;
extern long long L1D_total_cache_accesses;
extern long long L1D_total_cache_misses;
extern long long L1D_total_cache_pending_hits;
extern long long L1C_total_cache_accesses;
extern long long L1C_total_cache_misses;
extern long long L1C_total_cache_pending_hits;
extern long long L1C_total_cache_reservation_fails;
extern long long L1T_total_cache_accesses;
extern long long L1T_total_cache_misses;
extern long long L1T_total_cache_pending_hits;
extern long long L1T_total_cache_reservation_fails;
extern long long L2_total_cache_misses;
extern long long comp_inst_finish_time;
extern long long mem_inst_finish_time;
extern long long ibuffer_flush_count1;
extern long long ibuffer_flush_count2;
extern long long ibuffer_flush_count3;
extern long long replay_flush_count;
extern long long L1D_total_cache_reservation_fails;

extern long long present_ongoing_cycle;
extern long long opcode_tracer;

extern long long DEB_BUFFER_SIZE;

extern long long ICACHE_EMPTY_Kernel;
extern long long ICACHE_EMPTY_TOTAL;
extern long long L1I_miss_kernel;
extern long long L1I_hit_kernel;
extern long long L1I_miss_TOTAL;
extern long long L1I_hit_TOTAL; 
extern long long ibuffer_empty_TOTAL;
extern long long ibuffer_empty_kernel; 
extern long long gen_mem_icache_kernel;

extern bool stalled_on_DEB_dependence;
extern long long cannot_issue_warp_DEB_dep;
extern long long cannot_issue_warp_DEB_dep_kernel;

extern int inst_counter_warp;
extern int inst_counter_warp_dec;

extern long long tot_cycles_wb;
extern long long tot_cycles_wb_done;
extern long long inst_issued_sid_0;

extern int num_mem_fetch_generated;
extern int num_mem_fetch_generated_useful;
extern int fetch_misses;
extern int fetch_hits;
extern int fetch_resfail;
extern int control_hazard_count;
extern int control_hazard_count_kernel;

extern long long sync_inst_collision;
extern long long sync_inst_ibuffer_coll;
extern long long mem_inst_collision;
extern long long mem_inst_ibuffer_coll;

extern long long tot_inst_stuck;
extern long long memory_inst_stuck;
extern long long non_memory_inst_stuck;
extern long long load_inst_stuck;
extern long long store_inst_stuck;

extern long inst_exec_total;
extern long gpu_sim_insn_test;
extern long gpu_sim_insn_test_run;
